name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  GHP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: Install Node Packages
        run: npm ci
      - name: Validate Resume Schema
        run: npm run validate
      - name: Rename resume.html
        run: mv public/resume.html public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
